# Generated by Django 2.0 on 2020-05-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200526_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_class_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Class', models.ImageField(blank=True, max_length=255, null=True, upload_to='classroom')),
            ],
        ),
        migrations.AlterField(
            model_name='class_user',
            name='image_rep',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='class'),
        ),
        migrations.AlterField(
            model_name='image_user',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image'),
        ),
    ]
