# Generated by Django 2.0 on 2020-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200528_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_user',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
